// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/dopedao/dope-monorepo/packages/api/internal/ent/bodypart"
)

// BodyPart is the model entity for the BodyPart schema.
type BodyPart struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Type holds the value of the "type" field.
	Type bodypart.Type `json:"type,omitempty"`
	// Sex holds the value of the "sex" field.
	Sex bodypart.Sex `json:"sex,omitempty"`
	// Rle holds the value of the "rle" field.
	Rle string `json:"rle,omitempty"`
	// Sprite holds the value of the "sprite" field.
	Sprite string `json:"sprite,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BodyPartQuery when eager-loading is set.
	Edges        BodyPartEdges `json:"edges"`
	selectValues sql.SelectValues
}

// BodyPartEdges holds the relations/edges for other nodes in the graph.
type BodyPartEdges struct {
	// HustlerBodies holds the value of the hustler_bodies edge.
	HustlerBodies []*Hustler `json:"hustler_bodies,omitempty"`
	// HustlerHairs holds the value of the hustler_hairs edge.
	HustlerHairs []*Hustler `json:"hustler_hairs,omitempty"`
	// HustlerBeards holds the value of the hustler_beards edge.
	HustlerBeards []*Hustler `json:"hustler_beards,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
	// totalCount holds the count of the edges above.
	totalCount [3]map[string]int

	namedHustlerBodies map[string][]*Hustler
	namedHustlerHairs  map[string][]*Hustler
	namedHustlerBeards map[string][]*Hustler
}

// HustlerBodiesOrErr returns the HustlerBodies value or an error if the edge
// was not loaded in eager-loading.
func (e BodyPartEdges) HustlerBodiesOrErr() ([]*Hustler, error) {
	if e.loadedTypes[0] {
		return e.HustlerBodies, nil
	}
	return nil, &NotLoadedError{edge: "hustler_bodies"}
}

// HustlerHairsOrErr returns the HustlerHairs value or an error if the edge
// was not loaded in eager-loading.
func (e BodyPartEdges) HustlerHairsOrErr() ([]*Hustler, error) {
	if e.loadedTypes[1] {
		return e.HustlerHairs, nil
	}
	return nil, &NotLoadedError{edge: "hustler_hairs"}
}

// HustlerBeardsOrErr returns the HustlerBeards value or an error if the edge
// was not loaded in eager-loading.
func (e BodyPartEdges) HustlerBeardsOrErr() ([]*Hustler, error) {
	if e.loadedTypes[2] {
		return e.HustlerBeards, nil
	}
	return nil, &NotLoadedError{edge: "hustler_beards"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BodyPart) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case bodypart.FieldID, bodypart.FieldType, bodypart.FieldSex, bodypart.FieldRle, bodypart.FieldSprite:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BodyPart fields.
func (bp *BodyPart) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case bodypart.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				bp.ID = value.String
			}
		case bodypart.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				bp.Type = bodypart.Type(value.String)
			}
		case bodypart.FieldSex:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sex", values[i])
			} else if value.Valid {
				bp.Sex = bodypart.Sex(value.String)
			}
		case bodypart.FieldRle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field rle", values[i])
			} else if value.Valid {
				bp.Rle = value.String
			}
		case bodypart.FieldSprite:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sprite", values[i])
			} else if value.Valid {
				bp.Sprite = value.String
			}
		default:
			bp.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BodyPart.
// This includes values selected through modifiers, order, etc.
func (bp *BodyPart) Value(name string) (ent.Value, error) {
	return bp.selectValues.Get(name)
}

// QueryHustlerBodies queries the "hustler_bodies" edge of the BodyPart entity.
func (bp *BodyPart) QueryHustlerBodies() *HustlerQuery {
	return NewBodyPartClient(bp.config).QueryHustlerBodies(bp)
}

// QueryHustlerHairs queries the "hustler_hairs" edge of the BodyPart entity.
func (bp *BodyPart) QueryHustlerHairs() *HustlerQuery {
	return NewBodyPartClient(bp.config).QueryHustlerHairs(bp)
}

// QueryHustlerBeards queries the "hustler_beards" edge of the BodyPart entity.
func (bp *BodyPart) QueryHustlerBeards() *HustlerQuery {
	return NewBodyPartClient(bp.config).QueryHustlerBeards(bp)
}

// Update returns a builder for updating this BodyPart.
// Note that you need to call BodyPart.Unwrap() before calling this method if this BodyPart
// was returned from a transaction, and the transaction was committed or rolled back.
func (bp *BodyPart) Update() *BodyPartUpdateOne {
	return NewBodyPartClient(bp.config).UpdateOne(bp)
}

// Unwrap unwraps the BodyPart entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (bp *BodyPart) Unwrap() *BodyPart {
	_tx, ok := bp.config.driver.(*txDriver)
	if !ok {
		panic("ent: BodyPart is not a transactional entity")
	}
	bp.config.driver = _tx.drv
	return bp
}

// String implements the fmt.Stringer.
func (bp *BodyPart) String() string {
	var builder strings.Builder
	builder.WriteString("BodyPart(")
	builder.WriteString(fmt.Sprintf("id=%v, ", bp.ID))
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", bp.Type))
	builder.WriteString(", ")
	builder.WriteString("sex=")
	builder.WriteString(fmt.Sprintf("%v", bp.Sex))
	builder.WriteString(", ")
	builder.WriteString("rle=")
	builder.WriteString(bp.Rle)
	builder.WriteString(", ")
	builder.WriteString("sprite=")
	builder.WriteString(bp.Sprite)
	builder.WriteByte(')')
	return builder.String()
}

// NamedHustlerBodies returns the HustlerBodies named value or an error if the edge was not
// loaded in eager-loading with this name.
func (bp *BodyPart) NamedHustlerBodies(name string) ([]*Hustler, error) {
	if bp.Edges.namedHustlerBodies == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := bp.Edges.namedHustlerBodies[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (bp *BodyPart) appendNamedHustlerBodies(name string, edges ...*Hustler) {
	if bp.Edges.namedHustlerBodies == nil {
		bp.Edges.namedHustlerBodies = make(map[string][]*Hustler)
	}
	if len(edges) == 0 {
		bp.Edges.namedHustlerBodies[name] = []*Hustler{}
	} else {
		bp.Edges.namedHustlerBodies[name] = append(bp.Edges.namedHustlerBodies[name], edges...)
	}
}

// NamedHustlerHairs returns the HustlerHairs named value or an error if the edge was not
// loaded in eager-loading with this name.
func (bp *BodyPart) NamedHustlerHairs(name string) ([]*Hustler, error) {
	if bp.Edges.namedHustlerHairs == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := bp.Edges.namedHustlerHairs[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (bp *BodyPart) appendNamedHustlerHairs(name string, edges ...*Hustler) {
	if bp.Edges.namedHustlerHairs == nil {
		bp.Edges.namedHustlerHairs = make(map[string][]*Hustler)
	}
	if len(edges) == 0 {
		bp.Edges.namedHustlerHairs[name] = []*Hustler{}
	} else {
		bp.Edges.namedHustlerHairs[name] = append(bp.Edges.namedHustlerHairs[name], edges...)
	}
}

// NamedHustlerBeards returns the HustlerBeards named value or an error if the edge was not
// loaded in eager-loading with this name.
func (bp *BodyPart) NamedHustlerBeards(name string) ([]*Hustler, error) {
	if bp.Edges.namedHustlerBeards == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := bp.Edges.namedHustlerBeards[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (bp *BodyPart) appendNamedHustlerBeards(name string, edges ...*Hustler) {
	if bp.Edges.namedHustlerBeards == nil {
		bp.Edges.namedHustlerBeards = make(map[string][]*Hustler)
	}
	if len(edges) == 0 {
		bp.Edges.namedHustlerBeards[name] = []*Hustler{}
	} else {
		bp.Edges.namedHustlerBeards[name] = append(bp.Edges.namedHustlerBeards[name], edges...)
	}
}

// BodyParts is a parsable slice of BodyPart.
type BodyParts []*BodyPart
