// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dopedao/dope-monorepo/packages/api/internal/ent/dope"
	"github.com/dopedao/dope-monorepo/packages/api/internal/ent/item"
	"github.com/dopedao/dope-monorepo/packages/api/internal/ent/search"
	"github.com/dopedao/dope-monorepo/packages/api/internal/ent/wallet"
)

// DopeCreate is the builder for creating a Dope entity.
type DopeCreate struct {
	config
	mutation *DopeMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetClaimed sets the "claimed" field.
func (dc *DopeCreate) SetClaimed(b bool) *DopeCreate {
	dc.mutation.SetClaimed(b)
	return dc
}

// SetNillableClaimed sets the "claimed" field if the given value is not nil.
func (dc *DopeCreate) SetNillableClaimed(b *bool) *DopeCreate {
	if b != nil {
		dc.SetClaimed(*b)
	}
	return dc
}

// SetLastCheckedPaperClaim sets the "last_checked_paper_claim" field.
func (dc *DopeCreate) SetLastCheckedPaperClaim(t time.Time) *DopeCreate {
	dc.mutation.SetLastCheckedPaperClaim(t)
	return dc
}

// SetNillableLastCheckedPaperClaim sets the "last_checked_paper_claim" field if the given value is not nil.
func (dc *DopeCreate) SetNillableLastCheckedPaperClaim(t *time.Time) *DopeCreate {
	if t != nil {
		dc.SetLastCheckedPaperClaim(*t)
	}
	return dc
}

// SetOpened sets the "opened" field.
func (dc *DopeCreate) SetOpened(b bool) *DopeCreate {
	dc.mutation.SetOpened(b)
	return dc
}

// SetNillableOpened sets the "opened" field if the given value is not nil.
func (dc *DopeCreate) SetNillableOpened(b *bool) *DopeCreate {
	if b != nil {
		dc.SetOpened(*b)
	}
	return dc
}

// SetLastCheckedGearClaim sets the "last_checked_gear_claim" field.
func (dc *DopeCreate) SetLastCheckedGearClaim(t time.Time) *DopeCreate {
	dc.mutation.SetLastCheckedGearClaim(t)
	return dc
}

// SetNillableLastCheckedGearClaim sets the "last_checked_gear_claim" field if the given value is not nil.
func (dc *DopeCreate) SetNillableLastCheckedGearClaim(t *time.Time) *DopeCreate {
	if t != nil {
		dc.SetLastCheckedGearClaim(*t)
	}
	return dc
}

// SetScore sets the "score" field.
func (dc *DopeCreate) SetScore(i int) *DopeCreate {
	dc.mutation.SetScore(i)
	return dc
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (dc *DopeCreate) SetNillableScore(i *int) *DopeCreate {
	if i != nil {
		dc.SetScore(*i)
	}
	return dc
}

// SetRank sets the "rank" field.
func (dc *DopeCreate) SetRank(i int) *DopeCreate {
	dc.mutation.SetRank(i)
	return dc
}

// SetNillableRank sets the "rank" field if the given value is not nil.
func (dc *DopeCreate) SetNillableRank(i *int) *DopeCreate {
	if i != nil {
		dc.SetRank(*i)
	}
	return dc
}

// SetOrder sets the "order" field.
func (dc *DopeCreate) SetOrder(i int) *DopeCreate {
	dc.mutation.SetOrder(i)
	return dc
}

// SetBestAskPriceEth sets the "best_ask_price_eth" field.
func (dc *DopeCreate) SetBestAskPriceEth(f float64) *DopeCreate {
	dc.mutation.SetBestAskPriceEth(f)
	return dc
}

// SetNillableBestAskPriceEth sets the "best_ask_price_eth" field if the given value is not nil.
func (dc *DopeCreate) SetNillableBestAskPriceEth(f *float64) *DopeCreate {
	if f != nil {
		dc.SetBestAskPriceEth(*f)
	}
	return dc
}

// SetID sets the "id" field.
func (dc *DopeCreate) SetID(s string) *DopeCreate {
	dc.mutation.SetID(s)
	return dc
}

// SetWalletID sets the "wallet" edge to the Wallet entity by ID.
func (dc *DopeCreate) SetWalletID(id string) *DopeCreate {
	dc.mutation.SetWalletID(id)
	return dc
}

// SetNillableWalletID sets the "wallet" edge to the Wallet entity by ID if the given value is not nil.
func (dc *DopeCreate) SetNillableWalletID(id *string) *DopeCreate {
	if id != nil {
		dc = dc.SetWalletID(*id)
	}
	return dc
}

// SetWallet sets the "wallet" edge to the Wallet entity.
func (dc *DopeCreate) SetWallet(w *Wallet) *DopeCreate {
	return dc.SetWalletID(w.ID)
}

// AddItemIDs adds the "items" edge to the Item entity by IDs.
func (dc *DopeCreate) AddItemIDs(ids ...string) *DopeCreate {
	dc.mutation.AddItemIDs(ids...)
	return dc
}

// AddItems adds the "items" edges to the Item entity.
func (dc *DopeCreate) AddItems(i ...*Item) *DopeCreate {
	ids := make([]string, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return dc.AddItemIDs(ids...)
}

// SetIndexID sets the "index" edge to the Search entity by ID.
func (dc *DopeCreate) SetIndexID(id string) *DopeCreate {
	dc.mutation.SetIndexID(id)
	return dc
}

// SetNillableIndexID sets the "index" edge to the Search entity by ID if the given value is not nil.
func (dc *DopeCreate) SetNillableIndexID(id *string) *DopeCreate {
	if id != nil {
		dc = dc.SetIndexID(*id)
	}
	return dc
}

// SetIndex sets the "index" edge to the Search entity.
func (dc *DopeCreate) SetIndex(s *Search) *DopeCreate {
	return dc.SetIndexID(s.ID)
}

// Mutation returns the DopeMutation object of the builder.
func (dc *DopeCreate) Mutation() *DopeMutation {
	return dc.mutation
}

// Save creates the Dope in the database.
func (dc *DopeCreate) Save(ctx context.Context) (*Dope, error) {
	dc.defaults()
	return withHooks(ctx, dc.sqlSave, dc.mutation, dc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (dc *DopeCreate) SaveX(ctx context.Context) *Dope {
	v, err := dc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dc *DopeCreate) Exec(ctx context.Context) error {
	_, err := dc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dc *DopeCreate) ExecX(ctx context.Context) {
	if err := dc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (dc *DopeCreate) defaults() {
	if _, ok := dc.mutation.Claimed(); !ok {
		v := dope.DefaultClaimed
		dc.mutation.SetClaimed(v)
	}
	if _, ok := dc.mutation.Opened(); !ok {
		v := dope.DefaultOpened
		dc.mutation.SetOpened(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (dc *DopeCreate) check() error {
	if _, ok := dc.mutation.Claimed(); !ok {
		return &ValidationError{Name: "claimed", err: errors.New(`ent: missing required field "Dope.claimed"`)}
	}
	if _, ok := dc.mutation.Opened(); !ok {
		return &ValidationError{Name: "opened", err: errors.New(`ent: missing required field "Dope.opened"`)}
	}
	if _, ok := dc.mutation.Order(); !ok {
		return &ValidationError{Name: "order", err: errors.New(`ent: missing required field "Dope.order"`)}
	}
	return nil
}

func (dc *DopeCreate) sqlSave(ctx context.Context) (*Dope, error) {
	if err := dc.check(); err != nil {
		return nil, err
	}
	_node, _spec := dc.createSpec()
	if err := sqlgraph.CreateNode(ctx, dc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Dope.ID type: %T", _spec.ID.Value)
		}
	}
	dc.mutation.id = &_node.ID
	dc.mutation.done = true
	return _node, nil
}

func (dc *DopeCreate) createSpec() (*Dope, *sqlgraph.CreateSpec) {
	var (
		_node = &Dope{config: dc.config}
		_spec = sqlgraph.NewCreateSpec(dope.Table, sqlgraph.NewFieldSpec(dope.FieldID, field.TypeString))
	)
	_spec.OnConflict = dc.conflict
	if id, ok := dc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := dc.mutation.Claimed(); ok {
		_spec.SetField(dope.FieldClaimed, field.TypeBool, value)
		_node.Claimed = value
	}
	if value, ok := dc.mutation.LastCheckedPaperClaim(); ok {
		_spec.SetField(dope.FieldLastCheckedPaperClaim, field.TypeTime, value)
		_node.LastCheckedPaperClaim = value
	}
	if value, ok := dc.mutation.Opened(); ok {
		_spec.SetField(dope.FieldOpened, field.TypeBool, value)
		_node.Opened = value
	}
	if value, ok := dc.mutation.LastCheckedGearClaim(); ok {
		_spec.SetField(dope.FieldLastCheckedGearClaim, field.TypeTime, value)
		_node.LastCheckedGearClaim = value
	}
	if value, ok := dc.mutation.Score(); ok {
		_spec.SetField(dope.FieldScore, field.TypeInt, value)
		_node.Score = value
	}
	if value, ok := dc.mutation.Rank(); ok {
		_spec.SetField(dope.FieldRank, field.TypeInt, value)
		_node.Rank = value
	}
	if value, ok := dc.mutation.Order(); ok {
		_spec.SetField(dope.FieldOrder, field.TypeInt, value)
		_node.Order = value
	}
	if value, ok := dc.mutation.BestAskPriceEth(); ok {
		_spec.SetField(dope.FieldBestAskPriceEth, field.TypeFloat64, value)
		_node.BestAskPriceEth = value
	}
	if nodes := dc.mutation.WalletIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dope.WalletTable,
			Columns: []string{dope.WalletColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wallet.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.wallet_dopes = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := dc.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   dope.ItemsTable,
			Columns: dope.ItemsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := dc.mutation.IndexIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   dope.IndexTable,
			Columns: []string{dope.IndexColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(search.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Dope.Create().
//		SetClaimed(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DopeUpsert) {
//			SetClaimed(v+v).
//		}).
//		Exec(ctx)
func (dc *DopeCreate) OnConflict(opts ...sql.ConflictOption) *DopeUpsertOne {
	dc.conflict = opts
	return &DopeUpsertOne{
		create: dc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Dope.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (dc *DopeCreate) OnConflictColumns(columns ...string) *DopeUpsertOne {
	dc.conflict = append(dc.conflict, sql.ConflictColumns(columns...))
	return &DopeUpsertOne{
		create: dc,
	}
}

type (
	// DopeUpsertOne is the builder for "upsert"-ing
	//  one Dope node.
	DopeUpsertOne struct {
		create *DopeCreate
	}

	// DopeUpsert is the "OnConflict" setter.
	DopeUpsert struct {
		*sql.UpdateSet
	}
)

// SetClaimed sets the "claimed" field.
func (u *DopeUpsert) SetClaimed(v bool) *DopeUpsert {
	u.Set(dope.FieldClaimed, v)
	return u
}

// UpdateClaimed sets the "claimed" field to the value that was provided on create.
func (u *DopeUpsert) UpdateClaimed() *DopeUpsert {
	u.SetExcluded(dope.FieldClaimed)
	return u
}

// SetLastCheckedPaperClaim sets the "last_checked_paper_claim" field.
func (u *DopeUpsert) SetLastCheckedPaperClaim(v time.Time) *DopeUpsert {
	u.Set(dope.FieldLastCheckedPaperClaim, v)
	return u
}

// UpdateLastCheckedPaperClaim sets the "last_checked_paper_claim" field to the value that was provided on create.
func (u *DopeUpsert) UpdateLastCheckedPaperClaim() *DopeUpsert {
	u.SetExcluded(dope.FieldLastCheckedPaperClaim)
	return u
}

// ClearLastCheckedPaperClaim clears the value of the "last_checked_paper_claim" field.
func (u *DopeUpsert) ClearLastCheckedPaperClaim() *DopeUpsert {
	u.SetNull(dope.FieldLastCheckedPaperClaim)
	return u
}

// SetOpened sets the "opened" field.
func (u *DopeUpsert) SetOpened(v bool) *DopeUpsert {
	u.Set(dope.FieldOpened, v)
	return u
}

// UpdateOpened sets the "opened" field to the value that was provided on create.
func (u *DopeUpsert) UpdateOpened() *DopeUpsert {
	u.SetExcluded(dope.FieldOpened)
	return u
}

// SetLastCheckedGearClaim sets the "last_checked_gear_claim" field.
func (u *DopeUpsert) SetLastCheckedGearClaim(v time.Time) *DopeUpsert {
	u.Set(dope.FieldLastCheckedGearClaim, v)
	return u
}

// UpdateLastCheckedGearClaim sets the "last_checked_gear_claim" field to the value that was provided on create.
func (u *DopeUpsert) UpdateLastCheckedGearClaim() *DopeUpsert {
	u.SetExcluded(dope.FieldLastCheckedGearClaim)
	return u
}

// ClearLastCheckedGearClaim clears the value of the "last_checked_gear_claim" field.
func (u *DopeUpsert) ClearLastCheckedGearClaim() *DopeUpsert {
	u.SetNull(dope.FieldLastCheckedGearClaim)
	return u
}

// SetScore sets the "score" field.
func (u *DopeUpsert) SetScore(v int) *DopeUpsert {
	u.Set(dope.FieldScore, v)
	return u
}

// UpdateScore sets the "score" field to the value that was provided on create.
func (u *DopeUpsert) UpdateScore() *DopeUpsert {
	u.SetExcluded(dope.FieldScore)
	return u
}

// AddScore adds v to the "score" field.
func (u *DopeUpsert) AddScore(v int) *DopeUpsert {
	u.Add(dope.FieldScore, v)
	return u
}

// ClearScore clears the value of the "score" field.
func (u *DopeUpsert) ClearScore() *DopeUpsert {
	u.SetNull(dope.FieldScore)
	return u
}

// SetRank sets the "rank" field.
func (u *DopeUpsert) SetRank(v int) *DopeUpsert {
	u.Set(dope.FieldRank, v)
	return u
}

// UpdateRank sets the "rank" field to the value that was provided on create.
func (u *DopeUpsert) UpdateRank() *DopeUpsert {
	u.SetExcluded(dope.FieldRank)
	return u
}

// AddRank adds v to the "rank" field.
func (u *DopeUpsert) AddRank(v int) *DopeUpsert {
	u.Add(dope.FieldRank, v)
	return u
}

// ClearRank clears the value of the "rank" field.
func (u *DopeUpsert) ClearRank() *DopeUpsert {
	u.SetNull(dope.FieldRank)
	return u
}

// SetBestAskPriceEth sets the "best_ask_price_eth" field.
func (u *DopeUpsert) SetBestAskPriceEth(v float64) *DopeUpsert {
	u.Set(dope.FieldBestAskPriceEth, v)
	return u
}

// UpdateBestAskPriceEth sets the "best_ask_price_eth" field to the value that was provided on create.
func (u *DopeUpsert) UpdateBestAskPriceEth() *DopeUpsert {
	u.SetExcluded(dope.FieldBestAskPriceEth)
	return u
}

// AddBestAskPriceEth adds v to the "best_ask_price_eth" field.
func (u *DopeUpsert) AddBestAskPriceEth(v float64) *DopeUpsert {
	u.Add(dope.FieldBestAskPriceEth, v)
	return u
}

// ClearBestAskPriceEth clears the value of the "best_ask_price_eth" field.
func (u *DopeUpsert) ClearBestAskPriceEth() *DopeUpsert {
	u.SetNull(dope.FieldBestAskPriceEth)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Dope.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(dope.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DopeUpsertOne) UpdateNewValues() *DopeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(dope.FieldID)
		}
		if _, exists := u.create.mutation.Order(); exists {
			s.SetIgnore(dope.FieldOrder)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Dope.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DopeUpsertOne) Ignore() *DopeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DopeUpsertOne) DoNothing() *DopeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DopeCreate.OnConflict
// documentation for more info.
func (u *DopeUpsertOne) Update(set func(*DopeUpsert)) *DopeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DopeUpsert{UpdateSet: update})
	}))
	return u
}

// SetClaimed sets the "claimed" field.
func (u *DopeUpsertOne) SetClaimed(v bool) *DopeUpsertOne {
	return u.Update(func(s *DopeUpsert) {
		s.SetClaimed(v)
	})
}

// UpdateClaimed sets the "claimed" field to the value that was provided on create.
func (u *DopeUpsertOne) UpdateClaimed() *DopeUpsertOne {
	return u.Update(func(s *DopeUpsert) {
		s.UpdateClaimed()
	})
}

// SetLastCheckedPaperClaim sets the "last_checked_paper_claim" field.
func (u *DopeUpsertOne) SetLastCheckedPaperClaim(v time.Time) *DopeUpsertOne {
	return u.Update(func(s *DopeUpsert) {
		s.SetLastCheckedPaperClaim(v)
	})
}

// UpdateLastCheckedPaperClaim sets the "last_checked_paper_claim" field to the value that was provided on create.
func (u *DopeUpsertOne) UpdateLastCheckedPaperClaim() *DopeUpsertOne {
	return u.Update(func(s *DopeUpsert) {
		s.UpdateLastCheckedPaperClaim()
	})
}

// ClearLastCheckedPaperClaim clears the value of the "last_checked_paper_claim" field.
func (u *DopeUpsertOne) ClearLastCheckedPaperClaim() *DopeUpsertOne {
	return u.Update(func(s *DopeUpsert) {
		s.ClearLastCheckedPaperClaim()
	})
}

// SetOpened sets the "opened" field.
func (u *DopeUpsertOne) SetOpened(v bool) *DopeUpsertOne {
	return u.Update(func(s *DopeUpsert) {
		s.SetOpened(v)
	})
}

// UpdateOpened sets the "opened" field to the value that was provided on create.
func (u *DopeUpsertOne) UpdateOpened() *DopeUpsertOne {
	return u.Update(func(s *DopeUpsert) {
		s.UpdateOpened()
	})
}

// SetLastCheckedGearClaim sets the "last_checked_gear_claim" field.
func (u *DopeUpsertOne) SetLastCheckedGearClaim(v time.Time) *DopeUpsertOne {
	return u.Update(func(s *DopeUpsert) {
		s.SetLastCheckedGearClaim(v)
	})
}

// UpdateLastCheckedGearClaim sets the "last_checked_gear_claim" field to the value that was provided on create.
func (u *DopeUpsertOne) UpdateLastCheckedGearClaim() *DopeUpsertOne {
	return u.Update(func(s *DopeUpsert) {
		s.UpdateLastCheckedGearClaim()
	})
}

// ClearLastCheckedGearClaim clears the value of the "last_checked_gear_claim" field.
func (u *DopeUpsertOne) ClearLastCheckedGearClaim() *DopeUpsertOne {
	return u.Update(func(s *DopeUpsert) {
		s.ClearLastCheckedGearClaim()
	})
}

// SetScore sets the "score" field.
func (u *DopeUpsertOne) SetScore(v int) *DopeUpsertOne {
	return u.Update(func(s *DopeUpsert) {
		s.SetScore(v)
	})
}

// AddScore adds v to the "score" field.
func (u *DopeUpsertOne) AddScore(v int) *DopeUpsertOne {
	return u.Update(func(s *DopeUpsert) {
		s.AddScore(v)
	})
}

// UpdateScore sets the "score" field to the value that was provided on create.
func (u *DopeUpsertOne) UpdateScore() *DopeUpsertOne {
	return u.Update(func(s *DopeUpsert) {
		s.UpdateScore()
	})
}

// ClearScore clears the value of the "score" field.
func (u *DopeUpsertOne) ClearScore() *DopeUpsertOne {
	return u.Update(func(s *DopeUpsert) {
		s.ClearScore()
	})
}

// SetRank sets the "rank" field.
func (u *DopeUpsertOne) SetRank(v int) *DopeUpsertOne {
	return u.Update(func(s *DopeUpsert) {
		s.SetRank(v)
	})
}

// AddRank adds v to the "rank" field.
func (u *DopeUpsertOne) AddRank(v int) *DopeUpsertOne {
	return u.Update(func(s *DopeUpsert) {
		s.AddRank(v)
	})
}

// UpdateRank sets the "rank" field to the value that was provided on create.
func (u *DopeUpsertOne) UpdateRank() *DopeUpsertOne {
	return u.Update(func(s *DopeUpsert) {
		s.UpdateRank()
	})
}

// ClearRank clears the value of the "rank" field.
func (u *DopeUpsertOne) ClearRank() *DopeUpsertOne {
	return u.Update(func(s *DopeUpsert) {
		s.ClearRank()
	})
}

// SetBestAskPriceEth sets the "best_ask_price_eth" field.
func (u *DopeUpsertOne) SetBestAskPriceEth(v float64) *DopeUpsertOne {
	return u.Update(func(s *DopeUpsert) {
		s.SetBestAskPriceEth(v)
	})
}

// AddBestAskPriceEth adds v to the "best_ask_price_eth" field.
func (u *DopeUpsertOne) AddBestAskPriceEth(v float64) *DopeUpsertOne {
	return u.Update(func(s *DopeUpsert) {
		s.AddBestAskPriceEth(v)
	})
}

// UpdateBestAskPriceEth sets the "best_ask_price_eth" field to the value that was provided on create.
func (u *DopeUpsertOne) UpdateBestAskPriceEth() *DopeUpsertOne {
	return u.Update(func(s *DopeUpsert) {
		s.UpdateBestAskPriceEth()
	})
}

// ClearBestAskPriceEth clears the value of the "best_ask_price_eth" field.
func (u *DopeUpsertOne) ClearBestAskPriceEth() *DopeUpsertOne {
	return u.Update(func(s *DopeUpsert) {
		s.ClearBestAskPriceEth()
	})
}

// Exec executes the query.
func (u *DopeUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DopeCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DopeUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DopeUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: DopeUpsertOne.ID is not supported by MySQL driver. Use DopeUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DopeUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// DopeCreateBulk is the builder for creating many Dope entities in bulk.
type DopeCreateBulk struct {
	config
	err      error
	builders []*DopeCreate
	conflict []sql.ConflictOption
}

// Save creates the Dope entities in the database.
func (dcb *DopeCreateBulk) Save(ctx context.Context) ([]*Dope, error) {
	if dcb.err != nil {
		return nil, dcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(dcb.builders))
	nodes := make([]*Dope, len(dcb.builders))
	mutators := make([]Mutator, len(dcb.builders))
	for i := range dcb.builders {
		func(i int, root context.Context) {
			builder := dcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DopeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, dcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = dcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, dcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, dcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (dcb *DopeCreateBulk) SaveX(ctx context.Context) []*Dope {
	v, err := dcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dcb *DopeCreateBulk) Exec(ctx context.Context) error {
	_, err := dcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dcb *DopeCreateBulk) ExecX(ctx context.Context) {
	if err := dcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Dope.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DopeUpsert) {
//			SetClaimed(v+v).
//		}).
//		Exec(ctx)
func (dcb *DopeCreateBulk) OnConflict(opts ...sql.ConflictOption) *DopeUpsertBulk {
	dcb.conflict = opts
	return &DopeUpsertBulk{
		create: dcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Dope.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (dcb *DopeCreateBulk) OnConflictColumns(columns ...string) *DopeUpsertBulk {
	dcb.conflict = append(dcb.conflict, sql.ConflictColumns(columns...))
	return &DopeUpsertBulk{
		create: dcb,
	}
}

// DopeUpsertBulk is the builder for "upsert"-ing
// a bulk of Dope nodes.
type DopeUpsertBulk struct {
	create *DopeCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Dope.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(dope.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DopeUpsertBulk) UpdateNewValues() *DopeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(dope.FieldID)
			}
			if _, exists := b.mutation.Order(); exists {
				s.SetIgnore(dope.FieldOrder)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Dope.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DopeUpsertBulk) Ignore() *DopeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DopeUpsertBulk) DoNothing() *DopeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DopeCreateBulk.OnConflict
// documentation for more info.
func (u *DopeUpsertBulk) Update(set func(*DopeUpsert)) *DopeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DopeUpsert{UpdateSet: update})
	}))
	return u
}

// SetClaimed sets the "claimed" field.
func (u *DopeUpsertBulk) SetClaimed(v bool) *DopeUpsertBulk {
	return u.Update(func(s *DopeUpsert) {
		s.SetClaimed(v)
	})
}

// UpdateClaimed sets the "claimed" field to the value that was provided on create.
func (u *DopeUpsertBulk) UpdateClaimed() *DopeUpsertBulk {
	return u.Update(func(s *DopeUpsert) {
		s.UpdateClaimed()
	})
}

// SetLastCheckedPaperClaim sets the "last_checked_paper_claim" field.
func (u *DopeUpsertBulk) SetLastCheckedPaperClaim(v time.Time) *DopeUpsertBulk {
	return u.Update(func(s *DopeUpsert) {
		s.SetLastCheckedPaperClaim(v)
	})
}

// UpdateLastCheckedPaperClaim sets the "last_checked_paper_claim" field to the value that was provided on create.
func (u *DopeUpsertBulk) UpdateLastCheckedPaperClaim() *DopeUpsertBulk {
	return u.Update(func(s *DopeUpsert) {
		s.UpdateLastCheckedPaperClaim()
	})
}

// ClearLastCheckedPaperClaim clears the value of the "last_checked_paper_claim" field.
func (u *DopeUpsertBulk) ClearLastCheckedPaperClaim() *DopeUpsertBulk {
	return u.Update(func(s *DopeUpsert) {
		s.ClearLastCheckedPaperClaim()
	})
}

// SetOpened sets the "opened" field.
func (u *DopeUpsertBulk) SetOpened(v bool) *DopeUpsertBulk {
	return u.Update(func(s *DopeUpsert) {
		s.SetOpened(v)
	})
}

// UpdateOpened sets the "opened" field to the value that was provided on create.
func (u *DopeUpsertBulk) UpdateOpened() *DopeUpsertBulk {
	return u.Update(func(s *DopeUpsert) {
		s.UpdateOpened()
	})
}

// SetLastCheckedGearClaim sets the "last_checked_gear_claim" field.
func (u *DopeUpsertBulk) SetLastCheckedGearClaim(v time.Time) *DopeUpsertBulk {
	return u.Update(func(s *DopeUpsert) {
		s.SetLastCheckedGearClaim(v)
	})
}

// UpdateLastCheckedGearClaim sets the "last_checked_gear_claim" field to the value that was provided on create.
func (u *DopeUpsertBulk) UpdateLastCheckedGearClaim() *DopeUpsertBulk {
	return u.Update(func(s *DopeUpsert) {
		s.UpdateLastCheckedGearClaim()
	})
}

// ClearLastCheckedGearClaim clears the value of the "last_checked_gear_claim" field.
func (u *DopeUpsertBulk) ClearLastCheckedGearClaim() *DopeUpsertBulk {
	return u.Update(func(s *DopeUpsert) {
		s.ClearLastCheckedGearClaim()
	})
}

// SetScore sets the "score" field.
func (u *DopeUpsertBulk) SetScore(v int) *DopeUpsertBulk {
	return u.Update(func(s *DopeUpsert) {
		s.SetScore(v)
	})
}

// AddScore adds v to the "score" field.
func (u *DopeUpsertBulk) AddScore(v int) *DopeUpsertBulk {
	return u.Update(func(s *DopeUpsert) {
		s.AddScore(v)
	})
}

// UpdateScore sets the "score" field to the value that was provided on create.
func (u *DopeUpsertBulk) UpdateScore() *DopeUpsertBulk {
	return u.Update(func(s *DopeUpsert) {
		s.UpdateScore()
	})
}

// ClearScore clears the value of the "score" field.
func (u *DopeUpsertBulk) ClearScore() *DopeUpsertBulk {
	return u.Update(func(s *DopeUpsert) {
		s.ClearScore()
	})
}

// SetRank sets the "rank" field.
func (u *DopeUpsertBulk) SetRank(v int) *DopeUpsertBulk {
	return u.Update(func(s *DopeUpsert) {
		s.SetRank(v)
	})
}

// AddRank adds v to the "rank" field.
func (u *DopeUpsertBulk) AddRank(v int) *DopeUpsertBulk {
	return u.Update(func(s *DopeUpsert) {
		s.AddRank(v)
	})
}

// UpdateRank sets the "rank" field to the value that was provided on create.
func (u *DopeUpsertBulk) UpdateRank() *DopeUpsertBulk {
	return u.Update(func(s *DopeUpsert) {
		s.UpdateRank()
	})
}

// ClearRank clears the value of the "rank" field.
func (u *DopeUpsertBulk) ClearRank() *DopeUpsertBulk {
	return u.Update(func(s *DopeUpsert) {
		s.ClearRank()
	})
}

// SetBestAskPriceEth sets the "best_ask_price_eth" field.
func (u *DopeUpsertBulk) SetBestAskPriceEth(v float64) *DopeUpsertBulk {
	return u.Update(func(s *DopeUpsert) {
		s.SetBestAskPriceEth(v)
	})
}

// AddBestAskPriceEth adds v to the "best_ask_price_eth" field.
func (u *DopeUpsertBulk) AddBestAskPriceEth(v float64) *DopeUpsertBulk {
	return u.Update(func(s *DopeUpsert) {
		s.AddBestAskPriceEth(v)
	})
}

// UpdateBestAskPriceEth sets the "best_ask_price_eth" field to the value that was provided on create.
func (u *DopeUpsertBulk) UpdateBestAskPriceEth() *DopeUpsertBulk {
	return u.Update(func(s *DopeUpsert) {
		s.UpdateBestAskPriceEth()
	})
}

// ClearBestAskPriceEth clears the value of the "best_ask_price_eth" field.
func (u *DopeUpsertBulk) ClearBestAskPriceEth() *DopeUpsertBulk {
	return u.Update(func(s *DopeUpsert) {
		s.ClearBestAskPriceEth()
	})
}

// Exec executes the query.
func (u *DopeUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the DopeCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DopeCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DopeUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
