// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dopedao/dope-monorepo/packages/api/internal/ent/gamehustlerrelation"
	"github.com/dopedao/dope-monorepo/packages/api/internal/ent/predicate"
)

// GameHustlerRelationDelete is the builder for deleting a GameHustlerRelation entity.
type GameHustlerRelationDelete struct {
	config
	hooks    []Hook
	mutation *GameHustlerRelationMutation
}

// Where appends a list predicates to the GameHustlerRelationDelete builder.
func (ghrd *GameHustlerRelationDelete) Where(ps ...predicate.GameHustlerRelation) *GameHustlerRelationDelete {
	ghrd.mutation.Where(ps...)
	return ghrd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ghrd *GameHustlerRelationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ghrd.sqlExec, ghrd.mutation, ghrd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ghrd *GameHustlerRelationDelete) ExecX(ctx context.Context) int {
	n, err := ghrd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ghrd *GameHustlerRelationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(gamehustlerrelation.Table, sqlgraph.NewFieldSpec(gamehustlerrelation.FieldID, field.TypeString))
	if ps := ghrd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ghrd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ghrd.mutation.done = true
	return affected, err
}

// GameHustlerRelationDeleteOne is the builder for deleting a single GameHustlerRelation entity.
type GameHustlerRelationDeleteOne struct {
	ghrd *GameHustlerRelationDelete
}

// Where appends a list predicates to the GameHustlerRelationDelete builder.
func (ghrdo *GameHustlerRelationDeleteOne) Where(ps ...predicate.GameHustlerRelation) *GameHustlerRelationDeleteOne {
	ghrdo.ghrd.mutation.Where(ps...)
	return ghrdo
}

// Exec executes the deletion query.
func (ghrdo *GameHustlerRelationDeleteOne) Exec(ctx context.Context) error {
	n, err := ghrdo.ghrd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{gamehustlerrelation.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ghrdo *GameHustlerRelationDeleteOne) ExecX(ctx context.Context) {
	if err := ghrdo.Exec(ctx); err != nil {
		panic(err)
	}
}
